// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArDpYGWvAKGTVLSBYFcCefm5U2Fsk0ONU',
    appId: '1:36529435685:web:bbfb2d6f76179c4ff33bcc',
    messagingSenderId: '36529435685',
    projectId: 'notebloc-e4c29',
    authDomain: 'notebloc-e4c29.firebaseapp.com',
    storageBucket: 'notebloc-e4c29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOWbS5tg9nkL26y990k30-itI-oPYv53o',
    appId: '1:36529435685:android:52d1ce7dbb98651ff33bcc',
    messagingSenderId: '36529435685',
    projectId: 'notebloc-e4c29',
    storageBucket: 'notebloc-e4c29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGOAaDPj20mtKah2QNnB36cKdAtwvfMqg',
    appId: '1:36529435685:ios:729024bc69182395f33bcc',
    messagingSenderId: '36529435685',
    projectId: 'notebloc-e4c29',
    storageBucket: 'notebloc-e4c29.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGOAaDPj20mtKah2QNnB36cKdAtwvfMqg',
    appId: '1:36529435685:ios:258f17f79348b170f33bcc',
    messagingSenderId: '36529435685',
    projectId: 'notebloc-e4c29',
    storageBucket: 'notebloc-e4c29.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
